#pragma once
#include <ncurses.h>
#include <assert.h>

enum ENUM_COLORPAIR {
	ENUM_COLORPAIR_NONE = 0 ,
	ENUM_COLORPAIR_RECENTLY_HIT  ,
	ENUM_COLORPAIR_TERRAIN ,
	ENUM_COLORPAIR_TERRAIN_GREEN ,
	ENUM_COLORPAIR_OUT_OF_MAP_BOUNDS ,
};


#define ATTR_TERRAIN COLOR_PAIR(ENUM_COLORPAIR_TERRAIN)
#define ATTR_TERRAIN_GREEN COLOR_PAIR(ENUM_COLORPAIR_TERRAIN_GREEN)
#define ATTR_RECENTLY_HIT COLOR_PAIR(ENUM_COLORPAIR_RECENTLY_HIT)
#define ATTR_OUT_OF_MAP_BOUNDS  COLOR_PAIR(ENUM_COLORPAIR_OUT_OF_MAP_BOUNDS)
#define ATTR_TARGET  WA_REVERSE


void init_colorpairs(void);
